### ISSUE TITLE
有场地但是预约不了

### ISSUE THREAD

**Issue by JieJieJie-L** [GuotongWu/sustech-batminton-reserve#1]
提示系统异常

**Comment by JieJieJie-L** [comment]
报错截图在这：(https://github.com/GuotongWu/sustech-batminton-reserve/assets/135339516/d75948e4-a804-4298-83f2-bd506466da3a)

**Comment by Linkegee** [comment]
> 报错截图在这：(https://github.com/GuotongWu/sustech-batminton-reserve/assets/135339516/d75948e4-a804-4298-83f2-bd506466da3a)

这个报错应该是频繁请求被系统检测到了。封禁一天。

**Comment by lemon3242** [comment]
> > 报错截图在这：(https://github.com/GuotongWu/sustech-batminton-reserve/assets/135339516/d75948e4-a804-4298-83f2-bd506466da3a)
> 
> 这个报错应该是频繁请求被系统检测到了。封禁一天。

请问解决了吗？同样遇到系统异常的问题，但是没有被封禁账号。谢谢

**Comment by Linkegee** [comment]
解决了。已经提交pr。

**Comment by Linkegee** [comment]
解决了，已经提交pr。> > > 报错截图在这：(https://github.com/GuotongWu/sustech-batminton-reserve/assets/135339516/d75948e4-a804-4298-83f2-bd506466da3a)
> 
> > 
> 
> > 这个报错应该是频繁请求被系统检测到了。封禁一天。
> 
> 
> 
> 请问解决了吗？同样遇到系统异常的问题，但是没有被封禁账号。谢谢

**Comment by GuotongWu** [comment]
主分支已经更新，感谢@Linkegee的贡献
